apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.labels.app }}
  ports:
  - name: {{ .Values.backend.service.ports.name }}
    port: {{ .Values.backend.service.ports.port }}
    nodePort: {{ .Values.backend.service.ports.nodePort }}
    targetPort: {{ .Values.backend.service.ports.targetPort }}




